### ISSUE TITLE
Create a Profile Editing Form page in the template

### ISSUE THREAD

**Issue by returnoftheturk** [rawad663/presto#45]
Create a template with changing states that will allow a user/resto to edit their profile

**Comment by rawad663** [comment]
@returnoftheturk this one can be done in one of the following ways:

1. User that clicks on Edit is sent to the Signup page with the fields filled with the user data. The user can then change them and can click on the update button to send a PUT request.

2. User can manually edit fields in their profile by clicking an edit icon next to the fields

(2) is going to be more difficult to do but it would be a lot more user friendly.
